auto: true

markdown: kramdown
pygments: true
paginate: 8
permalink: /:title

title: lincode
url: http://lincode.github.io
feed: /atom.xml
author_info: <a href="http://lincode.github.io/">lincode</a>
