auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         10
permalink:        /:categories/:year/:month/:day/:title/

title:            "lincde's Blog"
url:              http://lincode.github.com
feed:             /feed.xml
author:
    name:         Name
    key:          yourdisquskey
description:      "述而不作"
copyright:        "CopryRight GuoJing 2012-2012 by GitHub and Jekyll"
headdesc:         "GuoJing的博客，关于设计，开发以及生活。"
headkeys:         "设计,开发,思考,生活,豆瓣,读书,电影,音乐,游记"